services:
  vaultwarden:
    container_name: vaultwarden-prod-1
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /data/docker/vaultwarden:/data/
    # ports:
    #   - 13080:80
    environment:
      ADMIN_TOKEN: $$argon2id$$v=19$$m=65540,t=3,p=4$$Example$$Examplexxxxxxxxxxxxxxxxxxxxx
      ORG_GROUPS_ENABLED: true
      ROCKET_WORKERS: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden-prod-1-http.entrypoints=web
      - traefik.http.routers.vaultwarden-prod-1-http.rule=Host(`vaultwarden.navigio.io`)
      - traefik.http.routers.vaultwarden-prod-1-https.entrypoints=websecure
      - traefik.http.routers.vaultwarden-prod-1-https.rule=Host(`vaultwarden.navigio.io`)
      - traefik.http.routers.vaultwarden-prod-1-https.tls=true
      - traefik.http.routers.vaultwarden-prod-1-https.tls.certresolver=route53
    networks:
      - frontend

networks:
  frontend:
    external: true
  backend:
    external: true
