services:
  uptime-kuma:
    container_name: uptimekuma-prod-1
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    extra_hosts:
      - "buchung.navigio.io:172.17.0.1"
    volumes:
      #- ./data:/app/data
      - /volume2/docker/uptimekuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.uptimekuma-prod-1-http.entrypoints=web
      - traefik.http.routers.uptimekuma-prod-1-http.rule=Host(`uptimekuma.navigio.io`)
      - traefik.http.routers.uptimekuma-prod-1-https.entrypoints=websecure
      - traefik.http.routers.uptimekuma-prod-1-https.rule=Host(`uptimekuma.navigio.io`)
      - traefik.http.routers.uptimekuma-prod-1-https.tls=true
      - traefik.http.routers.uptimekuma-prod-1-https.tls.certresolver=route53
    networks:
      - frontend
      - backend
      - dns-net

networks:
  frontend:
    external: true
  backend:
    external: true
  dns-net:
    external: true
