services:
  traefik:
    container_name: traefik-prod-1
    image: traefik:2.11.2
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /data/docker/traefik/conf/:/etc/traefik/conf/
      - /data/docker/traefik/certs/:/etc/traefik/certs/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_HOSTED_ZONE_ID
    restart: unless-stopped
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true
