http:
    routers:
        to-firewall:
            rule: "Host(`fw.navigio.io`)"
            tls:
                certResolver: route53
            service: firewall

    services:
        firewall:
            loadBalancer:
                servers:
                - url: https://192.168.0.1:8443
