services:
  paperless-redis:
    image: redis
    container_name: paperless-redis-prod-1
    restart: always
    volumes:
      - /data/docker/paperless/redis:/usr/local/etc/redis
    networks:
      - backend

  paperless-db:
    image: docker.io/library/postgres:16
    container_name: paperless-postgres-prod-1
    restart: always
    volumes:
      - /data/docker/paperless/pgdata-16:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - backend

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.11.0
    container_name: paperlessngx-prod-1
    restart: always
    depends_on:
      - paperless-db
      - paperless-redis
      - gotenberg
      - tika
    ports:
      - 11800:8000
    volumes:
      - /data/docker/paperless/data:/usr/src/paperless/data
      - /data/docker/paperless/media:/usr/src/paperless/media
      - /data/docker/paperless/export:/usr/src/paperless/export
      - /data/docker/paperless/consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PUID: 1000
      PGID: 1000
      PAPERLESS_DBHOST: paperless-db
      # PAPERLESS_ADMIN_USER: admin
      # PAPERLESS_ADMIN_PASSWORD: GEHEIM
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:11300
      PAPERLESS_TIKA_ENDPOINT: http://tika:11998
      # Zusätzliche Umgebungsvariablen ab hier:
      PAPERLESS_WORKER_TIMEOUT: 4000
    labels:
      - traefik.enable=true
      - traefik.http.routers.paperlessngx-prod-1-http.entrypoints=web
      - traefik.http.routers.paperlessngx-prod-1-http.rule=Host(`paperlessngx.navigio.io`)
      - traefik.http.routers.paperlessngx-prod-1-https.entrypoints=websecure
      - traefik.http.routers.paperlessngx-prod-1-https.rule=Host(`paperlessngx.navigio.io`)
      - traefik.http.routers.paperlessngx-prod-1-wss.rule=Host(`paperlessngx.navigio.io`)
      - traefik.http.routers.paperlessngx-prod-1-https.tls.certresolver=route53
      - traefik.http.routers.paperlessngx-prod-1-https.service=paperlessngx-prod-1
      - traefik.http.services.paperlessngx-prod-1.loadbalancer.server.port=8000
    networks:
      - frontend
      - backend

  gotenberg:
    image: gotenberg/gotenberg
    restart: always
    container_name: gotenberg-prod-1
    ports:
      - 11300:3000
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*
    networks:
      - backend
  
  tika:
    image: ghcr.io/paperless-ngx/tika
    container_name: tika-prod-1
    ports:
      - 11998:9998
    restart: always
    networks:
      - backend
    
networks:
  frontend:
    external: true
  backend:
    external: true
