services:
  traefik:
    container_name: traefik-prod-2
    image: traefik:3.0.3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 25:25
      - 465:465
      - 587:587
      - 993:993
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /data/docker/traefik/conf/:/etc/traefik/conf/
      - /data/docker/traefik/certs/:/etc/traefik/certs/
      - /data/docker/traefik/users/:/etc/traefik/users/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_HOSTED_ZONE_ID
    restart: unless-stopped
    networks:
      proxy:

networks:
  proxy:
    external: true
